### ISSUE TITLE
Call sign and frequency highlighting

### ISSUE THREAD

**Issue by riwim** [xssfox/flecode#1]
Hi all,

it seems that syntax highlighting has some problems correctly highlighting call signs and frequencies, e. g.:

<img width="174" alt="image" src="https://github.com/xssfox/flecode/assets/18545483/050eba48-8ec5-41cb-af0d-3453292181ad">

For the callsign, it seems that only the digit and the next character are highlighted. With the frequencies, I can't see any pattern. Any idea how to resolve this?

**Comment by xssfox** [comment]
What interesting timing of this issue. I only just noticed it last night when I was looking at some logs. The highlighting with my theme is much more subtle so I missed this in my initial release. I've just pushed 0.0.2 release that should fix this. Let me know how it goes.

**Comment by xssfox** [comment]
I've also added in date folding in 0.0.3 - would be nice to get your feedback on that as well

**Comment by riwim** [comment]
> The highlighting with my theme is much more subtle so I missed this in my initial release. I've just pushed 0.0.2 release that should fix this. Let me know how it goes.

I can confirm that when an item is highlighted, it is the time of the QSO and no longer parts of the callsign. Thank you!
However, this only works if the time precedes the frequency (1). If the frequency comes first, then no highlighting takes place (2):

![image](https://github.com/xssfox/flecode/assets/18545483/1a18a892-48a6-4f48-b45f-efd2e2b3d9a0)

However, both sequences are valid notations, which also generate valid logs:

![image](https://github.com/xssfox/flecode/assets/18545483/74236269-4d03-4f76-b4c2-254e756e4fc3)

I also noticed that of the header fields, all but one (_mypota_) of the ones [listed here](https://df3cb.com/fle/documentation/#headersection) are highlighted:

![image](https://github.com/xssfox/flecode/assets/18545483/60e1a804-b279-471f-981a-0a7fe00d1402)

Would you like to review these two points?

**Comment by riwim** [comment]
> I've also added in date folding in 0.0.3 - would be nice to get your feedback on that as well

I can confirm that date folding works. Nice feature!

**Comment by TheSkorm** [comment]
Thanks for the feedback! I'll try to get these sorted out

**Comment by xssfox** [comment]
0.0.5 should fix the two issues above.

Ok, that was fun. I've added in callsign syntax highlighting as it was a requirement to work out what was left and what was right of the callsign. I think I'm using roughly the same method as flecli so it should line up but there maybe some edge cases. I've also added gridsquares. there's a few edge cases where that might not work perfectly as well but it should capture most use cases.

<img width="566" alt="image" src="https://github.com/xssfox/flecode/assets/59047654/39efe421-9ac2-410f-9d10-2585f7a9ee35">

**Comment by riwim** [comment]
LGTM! 👍 

Regarding line 18 in your last screenshot: Did you know that you don't have to specify the name of the operator in the comment field, as with the @ sign there is a separate tag for it? ([ref](https://df3cb.com/fle/documentation/#other))

The author of the Windows software FLE also uses a separate highlighting for this purpose:
![image](https://github.com/xssfox/flecode/assets/18545483/1a9583e4-e023-4998-91a9-a9f585c69d1e)

**Comment by xssfox** [comment]
Ah this is just an example log from the flicli repo. I'll have a think about the name/@ syntax next release - I'd probably need to install the official client to see how the syntax highlighting works exactly
